function esc(value) {
  if (value === undefined || value === null || value === '') return '-';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function formatTimeStamp() {
  return new Date().toLocaleString('en-CA', { timeZone: 'America/Toronto' });
}

function sectionTitle(text) {
  return `<h2 style="font-size:14px;margin:20px 0 10px;color:#0f2b46;border-bottom:1px solid #dbe2ea;padding-bottom:6px;text-transform:uppercase;letter-spacing:.08em;">${esc(text)}</h2>`;
}

function pairGrid(pairs = []) {
  const cells = pairs
    .map(
      ({ label, value }) => `
      <div style="padding:10px;border:1px solid #dbe2ea;border-radius:6px;background:#fff;">
        <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px;">${esc(label)}</div>
        <div style="font-size:14px;color:#0f172a;font-weight:600;">${esc(value)}</div>
      </div>
    `,
    )
    .join('');

  return `<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;">${cells}</div>`;
}

function textareaBlock(label, value) {
  return `
    <div style="margin-top:10px;">
      <div style="font-size:11px;color:#64748b;text-transform:uppercase;letter-spacing:.08em;margin-bottom:4px;">${esc(label)}</div>
      <div style="min-height:70px;border:1px solid #dbe2ea;border-radius:6px;padding:10px;white-space:pre-wrap;line-height:1.45;">${esc(value)}</div>
    </div>
  `;
}

function wrapper(title, icon, subtitle, body, footer = 'Generated by MedicOS - Confidential') {
  return `
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>
      body { font-family: 'Arial', sans-serif; margin: 0; color: #0f172a; background: #ffffff; }
      .container { max-width: 100%; padding: 24px 28px 18px; }
      .header {
        background: #0f2b46;
        color: #fff;
        padding: 16px 20px;
        border-radius: 8px;
        display: flex;
        justify-content: space-between;
        align-items: center;
      }
      .title { font-size: 22px; font-weight: 700; margin: 0; }
      .subtitle { font-size: 12px; opacity: 0.92; margin-top: 4px; }
      .meta { font-size: 12px; text-align: right; }
      footer {
        margin-top: 20px;
        border-top: 1px solid #dbe2ea;
        padding-top: 10px;
        color: #64748b;
        font-size: 11px;
      }
      @media print {
        body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <div>
          <h1 class="title">${icon} ${esc(title)}</h1>
          <div class="subtitle">${esc(subtitle)}</div>
        </div>
        <div class="meta">
          Submitted<br />${esc(formatTimeStamp())}
        </div>
      </div>
      ${body}
      <footer>${esc(footer)}</footer>
    </div>
  </body>
</html>
`;
}

export function buildOccurrencePDFHTML(formData = {}, profile = {}) {
  const body = `
    ${sectionTitle('Incident Overview')}
    ${pairGrid([
      { label: 'Date', value: formData.date },
      { label: 'Time', value: formData.time },
      { label: 'Call Number', value: formData.call_number },
      { label: 'Classification', value: formData.classification },
      { label: 'Occurrence Type', value: formData.occurrence_type },
      { label: 'Occurrence Reference #', value: formData.occurrence_ref },
      { label: 'Classification Details', value: formData.classification_details },
      { label: 'Brief Description', value: formData.brief_description },
    ])}

    ${sectionTitle('Service & Vehicle')}
    ${pairGrid([
      { label: 'Service', value: formData.service || profile.service },
      { label: 'Vehicle #', value: formData.vehicle_number || profile.vehicleNumber },
      { label: 'Vehicle Description', value: formData.vehicle_description },
      { label: 'Role', value: formData.role || profile.role },
    ])}

    ${sectionTitle('Personnel')}
    ${pairGrid([
      { label: 'Badge #', value: formData.badge_number || profile.badgeNumber },
      { label: 'Fire Department Involved', value: formData.fire_department },
      { label: 'Police Involved', value: formData.police },
      { label: 'Role Description', value: formData.role_description },
    ])}

    ${sectionTitle('Report Details')}
    ${textareaBlock('Observation / Description of Event', formData.observation)}
    ${textareaBlock('Action Taken', formData.action_taken)}
    ${textareaBlock('Suggested Resolution', formData.suggested_resolution)}
    ${textareaBlock('Management Notes', formData.management_notes)}

    ${sectionTitle('Submission Information')}
    ${pairGrid([
      { label: 'Requested By', value: formData.requested_by },
      { label: 'Requested By - Details', value: formData.requested_by_details },
      { label: 'Report Creator', value: formData.report_creator || `${profile.firstName || ''} ${profile.lastName || ''}`.trim() },
      { label: 'Creator - Details', value: formData.creator_details },
    ])}
  `;

  return wrapper('EMS Occurrence Report', '⚕', 'Incident documentation for service operations', body);
}

export function buildTeddyBearPDFHTML(formData = {}, profile = {}) {
  const body = `
    <div style="margin-top:16px;font-size:13px;color:#475569;">Emergency Medical Services - Patient Comfort Tracking</div>
    <div style="margin-top:4px;font-size:12px;color:#64748b;font-style:italic;">Providing comfort when it matters most</div>
    <div style="margin-top:10px;font-size:12px;color:#0f2b46;font-family:'Courier New',monospace;">Form #: ${esc(formData.form_number)}</div>

    ${sectionTitle('Date & Time')}
    ${pairGrid([{ label: 'Date / Time', value: formData.date_time }])}

    ${sectionTitle('Primary Medic (Required)')}
    ${pairGrid([
      { label: 'First Name', value: formData.first_name || profile.firstName },
      { label: 'Last Name', value: formData.last_name || profile.lastName },
      { label: 'Medic Number', value: formData.medic_number || profile.medicNumber },
    ])}

    ${sectionTitle('Second Medic (Optional)')}
    ${pairGrid([
      { label: 'First Name', value: formData.second_first_name },
      { label: 'Last Name', value: formData.second_last_name },
      { label: 'Medic Number', value: formData.second_medic_number },
    ])}

    ${sectionTitle('Teddy Bear Recipient')}
    ${pairGrid([
      { label: 'Age', value: formData.recipient_age },
      { label: 'Gender', value: formData.recipient_gender },
      { label: 'Recipient Type', value: formData.recipient_type },
    ])}
  `;

  return wrapper('TEDDY BEAR COMFORT PROGRAM', '🧸', 'Comfort distribution tracking', body, 'Generated by MedicOS');
}

export function buildEmailHTML({ formType, formName, formData, profile, validation }) {
  const validationLine = validation?.canExport
    ? '<span style="color:#16a34a;font-weight:700;">Validation: PASS</span>'
    : '<span style="color:#dc2626;font-weight:700;">Validation: Review Required</span>';

  const top = `
    <p style="margin:0 0 10px;">Hello Team,</p>
    <p style="margin:0 0 10px;">A ${esc(formName)} has been prepared in MedicOS and is ready for review.</p>
    <p style="margin:0 0 14px;">${validationLine}</p>
    <p style="margin:0 0 14px;">
      Submitted by: <strong>${esc(`${profile.firstName || ''} ${profile.lastName || ''}`.trim())}</strong><br />
      Medic Number: <strong>${esc(profile.medicNumber)}</strong>
    </p>
  `;

  const rows = Object.entries(formData || {})
    .map(
      ([key, value]) =>
        `<tr><td style="border:1px solid #e2e8f0;padding:6px 8px;background:#f8fafc;font-size:12px;">${esc(key)}</td><td style="border:1px solid #e2e8f0;padding:6px 8px;font-size:12px;">${esc(value)}</td></tr>`,
    )
    .join('');

  return `
  <div style="font-family:Arial,sans-serif;color:#0f172a;line-height:1.45;">
    ${top}
    <table style="width:100%;border-collapse:collapse;margin-top:8px;">${rows}</table>
    <p style="margin-top:14px;">Regards,<br />MedicOS AI Assistant</p>
  </div>`;
}

export function applyTemplateValues(template, values = {}) {
  let out = template || '';
  for (const [key, value] of Object.entries(values)) {
    out = out.replaceAll(`{${key}}`, value ?? '');
  }
  return out;
}
